openapi: '3.0.2'
info:
  title: 'OpenAPI Course'
  version: '1.0'
  description: Specification for OpenAPI Course
  contact:
    name: Monbayashi
    email: test@test.com
  license:
    name: Apache 2.0
servers:
  - url: https://api.server.test/v1
    description: Development Server
paths:
  /v1/customers:
    get:
      responses:
        '200':
          description: List of Customers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                description: List of Customers
                items:
                  type: object
                  description: customer object
                  properties:
                    id:
                      type: string
                      format: uuid
                    firstName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: John
                    lastName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: Thompson
                    address:
                      type: object
                      properties:
                        line1:
                          type: string
                          example: 123 main
                        city:
                          type: string
                          example: St pete
                        stateCode:
                          type: string
                          minLength: 2
                          maxLength: 2
                          description: 2 Letter State Code
                          enum: [AL, AK, AZ, AR, CA]
                        zipCode:
                          type: string
                          example: 33701
                    
  /v1/beers:
    get:
      responses:
        '200':
          description: List of Beers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                description: List of Beers object
                items:
                  type: object
                  description: Beer object
                  properties:
                    name:
                      type: string
                    style:
                      type: string
                      enum:
                        - ALE
                        - PALE_ALE
                        - IPA
                        - WHEAT
                        - LAGER
                    upc:
                      type: string
                    price:
                      type: number
                    quantity_on_hand:
                      type: integer
                    brewery:
                      type: object
                      properties:
                        name:
                          type: string
                        location:
                          type: string
        '404':
          description: No Beers Found
          content: {}