openapi: '3.0.2'
info:
  title: 'OpenAPI Course'
  version: '1.0'
  description: Specification for OpenAPI Course
  contact:
    name: Monbayashi
    email: test@test.com
  license:
    name: Apache 2.0
servers:
  - url: https://api.server.test/v1
    description: Development Server
paths:
  /v1/customers:
    get:
      responses:
        '200':
          description: List of Customers
  /v1/beers:
    get:
      responses:
        '200':
          description: List of Beers
        '404':
          description: No Beers Found